### ISSUE TITLE
JsonDao documentation

### ISSUE THREAD

**Issue by ChristoRibeiro** [fehmicansaglam/reactivemongo-extensions#1]
Hi,

I think the documentation about JsonDao is not up to date, I cannot do that:

```
object PersonDao extends JsonDao[Person] {
  def db: DB = ???
  val collectionName: String = "persons"
}
```

instead of, I have to set more parameters to the dao object:

```
object MongoContext {
  def db: () => DB = () => ReactiveMongoPlugin.db
}

object PersonDao extends JsonDao[Person, BSONObjectID](MongoContext.db, "person")
```

**Comment by fehmicansaglam** [comment]
Yeah, documentation is unfortunately stale. I am going to update it tonight. But the examples in Introduction are correct. You can refer to them for the time being.

https://github.com/fehmicansaglam/reactivemongo-extensions#introduction

**Comment by ChristoRibeiro** [comment]
I tried your example, strangely I got an error: 

```
[error] /Users/chrissom/Workspace/test/TestDao/app/models/Person.scala:41: super constructor cannot be passed a self reference unless parameter is declared by-name
[error] object Person extends JsonDao[Person, BSONObjectID](MongoContext.db, "person") {
[error]               ^
```

The full code:

```
object MongoContext {
  def db: () => DB = () => ReactiveMongoPlugin.db
}

case class Person(_id: BSONObjectID = BSONObjectID.generate, name: String, surname: String, age: Int)

object Person extends JsonDao[Person, BSONObjectID](MongoContext.db, "person") {
  implicit val userFormat = Json.format[Person]
}
```

**Comment by fehmicansaglam** [comment]
Hmm. Before going deeper can you change the name of Person object to PersonDao?

**Comment by ChristoRibeiro** [comment]
I rename it but I get an error: `No Json formatter found for type models.Person. Try to implement an implicit Format for this type.`.

I use Play2, so I put a Json formatter inside my object: `implicit val userFormat = Json.format[Person]`.

**Comment by fehmicansaglam** [comment]
I see. The code below should work.

``` scala
object MongoContext {
  def db: () => DB = () => ReactiveMongoPlugin.db
}

case class Person(
  _id: BSONObjectID = BSONObjectID.generate, 
  name: String, 
  surname: String, 
  age: Int)

object Person {
  implicit val userFormat = Json.format[Person]
}

object PersonDao extends JsonDao[Person, BSONObjectID](MongoContext.db, "person") {
}
```

We can make your code work but I am trying to put together some best practices. I would suggest that companion object should not contain db related functions. These functions should be in a dao object. Companion object should provide helper functions for the model, like transformations, validation, etc.

**Comment by ChristoRibeiro** [comment]
Your right and the code compile and work :+1: 

However with autoIndexes method I get an ugly NPE:

```
Caused by: java.lang.NullPointerException: null
    at reactivemongo.extensions.dao.JsonDao.ensureIndexes(JsonDao.scala:40) ~[reactivemongo-extensions_2.10-0.10.0.1.jar:0.10.0.1]
    at reactivemongo.extensions.dao.JsonDao.<init>(JsonDao.scala:143) ~[reactivemongo-extensions_2.10-0.10.0.1.jar:0.10.0.1]
```

The DAO object:

```
object PersonDao extends JsonDao[Person, BSONObjectID](MongoContext.db, "person") {
  override val autoIndexes = Seq(
    Index(Seq("name" -> IndexType.Ascending), unique = true, background = true),
    Index(Seq("age" -> IndexType.Ascending), background = true)
  )
}
```

**Comment by fehmicansaglam** [comment]
If you want to set autoIndexes this way you need to use `override def autoIndexes`. In order to override val you should stick to the way used in the examples. 

``` scala
object PersonDao extends {
  override val autoIndexes = Seq(
    Index(Seq("name" -> IndexType.Ascending), unique = true, background = true),
    Index(Seq("age" -> IndexType.Ascending), background = true)
  )
} with JsonDao...
```

This is because of the initialization order in Scala.

**Comment by ChristoRibeiro** [comment]
Ok, I didn't know that on scala :) 

Anyway thanks for your time, everything work
