### ISSUE TITLE
Pass List Of Values In $in Query using `Query DSL`

### ISSUE THREAD

**Issue by harmeetsingh0013** [fehmicansaglam/reactivemongo-extensions#10]
I am trying to query the data using $in query with query DSL, but the return values are empty. Because i pass the list of values to the $in query. Please click on this link for more detail: 

http://stackoverflow.com/questions/30082310/reactive-mongo-extensions-pass-list-of-values-in-in-query-using-query-dsl

**Comment by fehmicansaglam** [comment]
@harmeetsingh0013 I have posted an answer to SO. And as I said before, this project has moved to here: https://github.com/ReactiveMongo/ReactiveMongo-Extensions
