### ISSUE TITLE
Migrate 0.10 to 0.11.7: Provide migration guide from 0.10 to 0.11. 

### ISSUE THREAD

**Issue by harmeetsingh0013** [fehmicansaglam/reactivemongo-extensions#12]
I want to migrate my application to mongodb 3. That's why i need to use 0.11.7 version. But the problem is that, when i trying to migrate the application with new depedencies i got an errors. There is no proper study guide for migration. Please provide a proper migration guide. my errors are like: 

```
No Json serializer found for type reactivemongo.bson.BSONDateTime. Try to implement an implicit Writes or Format for this type
```

**Comment by fehmicansaglam** [comment]
Wrong project. :point_right: https://github.com/ReactiveMongo/ReactiveMongo-Extensions
