### ISSUE TITLE
Temporal informations

### ISSUE THREAD

**Issue by ChristoRibeiro** [fehmicansaglam/reactivemongo-extensions#5]
Feature idea:

Ability to add easily temporal informations (createdAd and updatedAt) on a document. On each insert/update/save methods call, temporal informations will be updated.

Toy example:

```
case class User(name: String) extends TemporalSupport

val newUser = UserDao.insert(User("chrissom"))

newUser.createdAt // give a DateTime
newUser.updatedAt // give a DateTime

val updateUser = UserDao.save(newUser)

updateUser.createdAt // give same previous DateTime
updateUser.updatedAt // give a new DateTime
```

**Comment by fehmicansaglam** [comment]
It is actually not an easy task. http://stackoverflow.com/questions/23198116/is-it-possible-to-update-fields-of-any-case-class-implementing-a-common-trait

I was planning to provide that lifecyle via a typeclass.

**Comment by ChristoRibeiro** [comment]
In 0.10.0.4-SNAPSHOT the LifeCycle looks very nice! 

Update (update, updateById, findAndUpdate...) functions are not concerned about LifeCycle?

**Comment by fehmicansaglam** [comment]
Update functions may take a case class(model) or an update modifier. This is not easy to handle.

Lifecycle should:

a. call the event if the param is a case class.
b. do nothing if the param is an update modifier or modify the update query.

As this is inconsistent behavior I didn't include update functions. What do you think?

**Comment by ChristoRibeiro** [comment]
I did not thought about update modifier... You're right :( Like you said above, it's not an easy task.

I'll try some things in coming days... as soon as I get time.
