### ISSUE TITLE
Artifact for Scala 2.11

### ISSUE THREAD

**Issue by ChristoRibeiro** [fehmicansaglam/reactivemongo-extensions#6]
Hello,

I tried to update my project to Play 2.3 and I get an error on dependencies et the Scala version.

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: net.fehmicansaglam#reactivemongo-extensions-json_2.11;0.10.0.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

You know if reactivemongo-extension works with Scala 2.11? and if yes, he could be possible to push the artifact?

**Comment by fehmicansaglam** [comment]
Currently there is no support for Scala 2.11. Although the project has moved to https://github.com/ReactiveMongo/ReactiveMongo-Extensions I am going to make a release based on 0.10.5.akka23-SNAPSHOT tonight, ~after 12 hours.

**Comment by ChristoRibeiro** [comment]
Great news, the project become an official ReactiveMongo project ?

I will check on my side about Scala 2.1. I keep you in touch.

**Comment by fehmicansaglam** [comment]
Yes, we are trying to push a snapshot soon.

**Comment by fehmicansaglam** [comment]
I have released a snapshot for Scala 2.11

``` scala
resolvers += "Sonatype Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies ++= Seq(
  "net.fehmicansaglam" %% "reactivemongo-extensions-json" % "0.10.5.akka23-SNAPSHOT"
)
```

**Comment by Tvaroh** [comment]
I don't see findAndUpdate/findAndRemove methods in this build. Not sure if they exist in 2.10 release.

@fehmicansaglam could you please comment on this?

**Comment by fehmicansaglam** [comment]
No, they are not. But I think I can backport them to this branch today.

**Comment by Tvaroh** [comment]
@fehmicansaglam may be you better create Scala 2.11 release of the up to date code?

**Comment by fehmicansaglam** [comment]
Yep, I will.

**Comment by Tvaroh** [comment]
@fehmicansaglam thanks you so much!

**Comment by fehmicansaglam** [comment]
Done.

**Comment by Tvaroh** [comment]
@fehmicansaglam 

I get this NPE when ensureIndexes() is called (I don't use autoIndexes):

```
Caused by: java.lang.NullPointerException
    at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:332)
    at scala.concurrent.Future$class.map(Future.scala:235)
    at scala.concurrent.impl.Promise$KeptPromise.map(Promise.scala:322)
    at scala.concurrent.Future$.sequence(Future.scala:500)
    at reactivemongo.extensions.dao.BsonDao.ensureIndexes(BsonDao.scala:85)
    at reactivemongo.extensions.dao.BsonDao.<init>(BsonDao.scala:258)
```

**Comment by Tvaroh** [comment]
My fault. ExecutorContext should be set like this:

``` scala
class CVDaoMongo extends { override val ec: ExecutionContext = asyncContext } with BsonDao[CVRecord, BSONObjectID](db _, "cv") with CVDao
```

BTW, why do use pass db parameter as a function? You can use `=> DB` if you need lazy init.

**Comment by fehmicansaglam** [comment]
Just importing the default ExecutionContext should work. Have you tried that?

``` scala
import scala.concurrent.ExecutionContext.Implicits.global
```

I wanted the db parameter not to be a val(lazy or not) but a function with possible side effects.

**Comment by Tvaroh** [comment]
I have predefined execution contexts for async and blocking operations within my cake, I don't use the global one.

Also this throws:

``` scala
      val selector = mkQuery(owner, language)
      findRandom(selector) map { recordOpt =>
        recordOpt map { record =>
          (record.cv, record.version, record.lastModified, record.lastModifiedBy)
        }
      }
```

Exception:

```
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at scala.util.Random.nextInt(Random.scala:66)
    at reactivemongo.extensions.dao.BsonDao$$anonfun$findRandom$1.apply(BsonDao.scala:159)
    at reactivemongo.extensions.dao.BsonDao$$anonfun$findRandom$1.apply(BsonDao.scala:158)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
    at scala.util.Try$.apply(Try.scala:191)
    at scala.util.Success.map(Try.scala:236)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Original code that works:

``` scala
      val selector = mkQuery(owner, language)
      cvDraftColl.find(selector).cursor[BSONDocument].headOption map { docOpt =>
        docOpt map { doc =>
          val record = doc.as[CVRecord]
          (record.cv, record.version, record.lastModified, record.lastModifiedBy)
        }
      }
```

**Comment by fehmicansaglam** [comment]
I see. I should have written a test case for custom ExecutionContext. I will also add it to docs. 
Can you file an issue for that findRandom bug?

**Comment by Tvaroh** [comment]
Yes, sure. This is the only place where `findRandom` fails, I don't know why - in other DAOs it works (I tried to migrate 5-6 of them).

Regarding overriding `ensureIndexes` and `ec` before the body (don't remember how this feature is called). I think it's better to think twice before exposing it as a public API. You probably can get rid of this requirement. Also, passing `db` parameter is just passing parameter - it shouldn't be a function with side-effects.

In any case thanks for your efforts, I'm sure this library has a nice future.

**Comment by fehmicansaglam** [comment]
I like early initialization syntax for autoIndexes. I find it more readable. But you are right for `ec`.

I am not sure for `db`. I will think about it.

**Comment by fehmicansaglam** [comment]
Regarding the findRandom issue, if the selector does not match any document the call will fail. I am going to fix it.

**Comment by Tvaroh** [comment]
Oh yes, this is the case. Please, update the snapshot after the fix. Thanks.

**Comment by fehmicansaglam** [comment]
Released.

**Comment by Tvaroh** [comment]
Awesome, thank you.
